webserver:
   container_name: woocommerce
   image: shipbeat/woocommerce
   links:
    - dbserver:mysql
   ports:
    - 8080:80
   volumes:
    - ./:/var/www/html/wp-content/plugins/co2ok-plugin-woocommerce/

dbserver:
   container_name: woo_mariadb
   image: mariadb
   environment:
    MYSQL_ROOT_PASSWORD: example
   ports:
    - 3307:3306
